id: org.eclipse.che.editor.jupyter
version: 1.0.0
type: Che Editor
name: jupyter-notebook
title: Jupyter Notebook as Editor for Eclipse Che
description: Jupyter Notebook as Editor for Eclipse Che
icon: https://jupyter.org/assets/main-logo.svg
url: http://che-plugin-registry-eclipse-che.172.17.0.1.nip.io/plugins/org.eclipse.che.editor.jupyter/1.0.0/che-plugin-yaml.tar.gz
